import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  backBtn: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginRight: 15,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1a3b5c",
  },
  headerSubtitle: {
    fontSize: 13,
    color: "#7a8b9a",
    marginTop: 2,
  },
  clipboardIcon: {
    width: 60,
    height: 60,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  cardIcon: {
    marginRight: 10,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#1a3b5c",
  },
  cardSubtitle: {
    fontSize: 13,
    color: "#7a8b9a",
    marginBottom: 15,
  },
  optionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  optionItem: {
    width: "31%",
    aspectRatio: 1,
    borderRadius: 15,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "transparent",
  },
  optionText: {
    fontSize: 12,
    marginTop: 5,
    fontWeight: "500",
    color: "#333",
  },
  intensityContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  intensityItem: {
    alignItems: "center",
    padding: 8,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "transparent",
  },
  intensityNumber: {
    fontSize: 12,
    fontWeight: "bold",
    marginTop: 4,
  },
  intensityLabel: {
    fontSize: 10,
    color: "#7a8b9a",
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 10,
  },
  tag: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#f0f4f8",
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e1e8ed",
  },
  tagActive: {
    backgroundColor: "#e8f0fe",
    borderColor: "#4285f4",
  },
  tagText: {
    fontSize: 13,
    color: "#555",
  },
  tagTextActive: {
    color: "#1a3b5c",
    fontWeight: "bold",
  },
  input: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 15,
    fontSize: 14,
    color: "#333",
    borderWidth: 1,
    borderColor: "#eee",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  saveBtn: {
    backgroundColor: "#ffdc80",
    paddingVertical: 16,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  saveBtnText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1a3b5c",
    marginRight: 8,
  },
  // Relatórios
  reportCard: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 2,
  },
  reportDateInfo: {
    marginRight: 15,
    alignItems: "center",
    paddingRight: 15,
    borderRightWidth: 1,
    borderRightColor: "#eee",
  },
  reportDay: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1a3b5c",
  },
  reportMonth: {
    fontSize: 12,
    color: "#7a8b9a",
    textTransform: "uppercase",
  },
  reportContent: {
    flex: 1,
  },
  reportType: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  reportTime: {
    fontSize: 12,
    color: "#7a8b9a",
    marginTop: 2,
  },
  reportIntensity: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  intensityValue: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 100,
  },
  emptyText: {
    fontSize: 16,
    color: "#7a8b9a",
    marginTop: 15,
    textAlign: "center",
  },
  // Modal de Detalhes
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    width: '100%',
    maxHeight: '85%',
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    paddingBottom: 15,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a3b5c',
  },
  closeBtn: {
    padding: 5,
  },
  detailSection: {
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#6a7fdb',
    marginLeft: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 16,
    color: '#333',
    lineHeight: 24,
    backgroundColor: '#f8f9fa',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee',
  },
  detailTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 5,
  },
  detailTag: {
    backgroundColor: '#e8f0fe',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    marginRight: 6,
    marginBottom: 6,
  },
  detailTagText: {
    fontSize: 12,
    color: '#1a3b5c',
    fontWeight: '600',
  },
  intensityBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
    marginLeft: 10,
  },
  intensityBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
});
