import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 40,
  },
  bannerContainer: {
    height: 200,
    backgroundColor: "#ffffff",
    marginBottom: 20,
    borderRadius: 30,
    overflow: "hidden",
    marginLeft: -20,
    marginRight: -20,
    shadowColor: "#000",
    shadowOpacity: 0.5,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 0 },
    elevation: 50,
  },
  bannerImage: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
  },
  backBtnOnBanner: {
    position: "absolute",
    top: 35,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  headerSection: {
    marginBottom: 20,
    marginTop: 0,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#3b4352",
    marginBottom: 5,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 17,
    color: "#5b6574",
    textAlign: "center",
  },
  courseCard: {
    backgroundColor: "#64b4f68c",
    borderRadius: 26,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOpacity: 0.0,
    shadowRadius: 18,
    elevation: 0,
  },
  progressCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 20,
  },
  topicsCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 20,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  progressPercentage: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#3b4352",
    marginRight: 12,
  },
  progressBarBg: {
    flex: 1,
    height: 20,
    backgroundColor: "#e6ebf0",
    borderRadius: 40,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#4caf50",
    borderRadius: 4,
  },
  moduleInfo: {
    fontSize: 13,
    color: "#5b6574",
    fontWeight: "600",
    marginBottom: 15,
    textAlign: "center",
  },
  certificateBtn: {
    backgroundColor: "#3B82F6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 5,
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  certificateBtnDisabled: {
    backgroundColor: "#EDF2F7",
    shadowOpacity: 0,
    elevation: 0,
  },
  certificateBtnText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
  },
  certificateBtnTextDisabled: {
    color: "#A0AEC0",
  },
  moduleSection: {
    marginBottom: 20,
  },
  moduleTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#f2f5faff",
    marginBottom: 12,
    paddingHorizontal: 5,
  },
  topicItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginBottom: 5,
  },
  topicDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#e0e7ee",
    marginRight: 12,
  },
  topicDotCompleted: {
    backgroundColor: "#4caf50",
  },
  topicText: {
    fontSize: 14,
    color: "#5b6574",
    flex: 1,
    lineHeight: 20,
  },
  topicSeparator: {
    height: 1,
    backgroundColor: "#e0e7ee",
    marginHorizontal: 15,
    marginBottom: 10,
  },
  helpCard: {
    backgroundColor: "#e3f2fd",
    borderRadius: 16,
    padding: 20,
    marginTop: 10,
    marginBottom: 20,
  },
  helpHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  helpTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#3b4352",
    marginLeft: 8,
  },
  helpText: {
    fontSize: 14,
    color: "#5b6574",
    marginBottom: 12,
    lineHeight: 20,
  },
  forumBtn: {
    backgroundColor: "#64b5f6",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  forumBtnText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#ffffff",
  },
});
